"""
output/formatter.py
Formats documentation into Markdown, HTML, or JSON output.
HTML output is a fully self-contained, professional SDK documentation site.
"""

import json
import re
import html as html_module
from datetime import datetime
from typing import Dict, Optional


# ---------------------------------------------------------------------------
# Markdown output
# ---------------------------------------------------------------------------

def format_markdown(sections: Dict[str, str], analysis: Dict) -> str:
    timestamp = datetime.now().strftime("%Y-%m-%d")
    parts = [f"<!-- Generated by Agentic Documentation Generator on {timestamp} -->", ""]

    section_order = [
        "overview", "installation", "usage_guide", "api_docs",
        "architecture", "examples", "configuration", "contributing", "changelog",
    ]
    for key in section_order:
        if key in sections and sections[key]:
            parts.append(sections[key])
            parts.append("")
            parts.append("---")
            parts.append("")
    for key, content in sections.items():
        if key not in section_order and content:
            parts.append(content)
            parts.append("")

    parts.append(f"*Documentation generated on {timestamp}*")
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# JSON output
# ---------------------------------------------------------------------------

def format_json(sections: Dict[str, str], analysis: Dict) -> str:
    output = {
        "metadata": {
            "project_name": analysis.get("project_name", "unknown"),
            "generated_at": datetime.now().isoformat(),
            "generator": "Agentic Documentation Generator",
            "language": analysis.get("language", "unknown"),
            "framework": analysis.get("framework", "unknown"),
            "architecture": analysis.get("architecture", "unknown"),
            "complexity": analysis.get("complexity", "unknown"),
            "total_files_analyzed": analysis.get("total_files", 0),
        },
        "analysis": {
            "description": analysis.get("description", ""),
            "features": analysis.get("features", []),
            "key_components": analysis.get("key_components", []),
            "dependencies": analysis.get("dependencies", []),
            "entry_points": analysis.get("entry_points", []),
        },
        "documentation": {k: v for k, v in sections.items() if v},
    }
    return json.dumps(output, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# HTML output — professional SDK documentation site
# ---------------------------------------------------------------------------

def format_html(sections: Dict[str, str], analysis: Dict) -> str:
    project_name = analysis.get("project_name", "Project Documentation")
    description  = analysis.get("description", "")
    timestamp    = datetime.now().strftime("%B %d, %Y")
    language     = analysis.get("language", "")
    framework    = analysis.get("framework", "")
    complexity   = analysis.get("complexity", "")
    total_files  = analysis.get("total_files", 0)

    section_order = [
        ("overview",      "Overview"),
        ("installation",  "Installation"),
        ("usage_guide",   "Usage Guide"),
        ("api_docs",      "API Reference"),
        ("architecture",  "Architecture"),
        ("examples",      "Examples"),
        ("configuration", "Configuration"),
        ("contributing",  "Contributing"),
        ("changelog",     "Changelog"),
    ]

    # Sidebar nav items
    nav_items_html = ""
    for key, label in section_order:
        if key in sections and sections[key]:
            icon = {
                "overview": "◈", "installation": "⬇", "usage_guide": "▶",
                "api_docs": "⊞", "architecture": "⬡", "examples": "◉",
                "configuration": "⚙", "contributing": "♦", "changelog": "◷",
            }.get(key, "•")
            nav_items_html += f'<li><a href="#{key}" class="nav-link" data-section="{key}"><span class="nav-icon">{icon}</span>{label}</a></li>\n'

    # Content sections
    content_html = ""
    for key, label in section_order:
        if key in sections and sections[key]:
            rendered = _markdown_to_html(sections[key])
            content_html += f'<section id="{key}" class="doc-section"><div class="section-inner">{rendered}</div></section>\n'

    # Header badges
    badges = ""
    if language:
        badges += f'<span class="badge badge-lang"><span class="badge-dot"></span>{html_module.escape(language)}</span>'
    if framework and framework not in ("unknown", "none", ""):
        badges += f'<span class="badge badge-framework"><span class="badge-dot"></span>{html_module.escape(framework)}</span>'
    if complexity and complexity not in ("unknown", ""):
        badges += f'<span class="badge badge-complexity"><span class="badge-dot"></span>{html_module.escape(complexity.title())} complexity</span>'
    if total_files:
        badges += f'<span class="badge badge-files"><span class="badge-dot"></span>{total_files} files</span>'

    # Stats for hero
    feature_count = len(analysis.get("features", []))
    dep_count     = len(analysis.get("dependencies", []))
    comp_count    = len(analysis.get("key_components", []))

    return f"""<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{html_module.escape(project_name)} — SDK Docs</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<style>
/* ── Reset & Tokens ────────────────────────────────────────────────────── */
*, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

:root {{
  /* Brand */
  --accent:        #7c3aed;
  --accent-light:  #8b5cf6;
  --accent-dim:    #4c1d95;
  --accent-glow:   rgba(124,58,237,0.25);
  --teal:          #06b6d4;
  --teal-dim:      rgba(6,182,212,0.15);
  --green:         #10b981;
  --green-dim:     rgba(16,185,129,0.15);
  --amber:         #f59e0b;
  --red:           #ef4444;

  /* Surface */
  --bg-base:       #060910;
  --bg-surface:    #0d1117;
  --bg-raised:     #161b22;
  --bg-overlay:    #1c2333;
  --bg-hover:      #21262d;

  /* Sidebar */
  --sidebar-w:     272px;
  --sidebar-bg:    #0a0d13;
  --sidebar-border:#1a2030;

  /* Header */
  --header-h:      58px;
  --header-bg:     rgba(6,9,16,0.92);

  /* Text */
  --text-primary:  #e6edf3;
  --text-secondary:#8b949e;
  --text-muted:    #484f58;
  --text-accent:   #a78bfa;

  /* Borders */
  --border:        #21262d;
  --border-muted:  #161b22;

  /* Code */
  --code-bg:       #0d1117;
  --code-border:   #30363d;
  --code-text:     #e6edf3;
  --inline-bg:     #1f2937;
  --inline-text:   #a78bfa;

  /* Syntax */
  --syn-keyword:   #ff7b72;
  --syn-string:    #a5d6ff;
  --syn-comment:   #6e7681;
  --syn-number:    #79c0ff;
  --syn-function:  #d2a8ff;
  --syn-class:     #ffa657;
  --syn-decorator: #79c0ff;
  --syn-builtin:   #ffa657;
  --syn-operator:  #ff7b72;
  --syn-param:     #e6edf3;

  /* Animation */
  --ease:          cubic-bezier(0.16, 1, 0.3, 1);
}}

/* ── Base ──────────────────────────────────────────────────────────────── */
html {{ scroll-behavior: smooth; }}

body {{
  font-family: 'Inter', system-ui, sans-serif;
  background: var(--bg-base);
  color: var(--text-primary);
  min-height: 100vh;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}}

/* ── Scrollbar ─────────────────────────────────────────────────────────── */
::-webkit-scrollbar {{ width: 6px; height: 6px; }}
::-webkit-scrollbar-track {{ background: transparent; }}
::-webkit-scrollbar-thumb {{ background: #30363d; border-radius: 3px; }}
::-webkit-scrollbar-thumb:hover {{ background: #484f58; }}

/* ── Scroll progress bar ───────────────────────────────────────────────── */
#scroll-progress {{
  position: fixed;
  top: 0; left: 0;
  height: 2px;
  width: 0%;
  background: linear-gradient(90deg, var(--accent), var(--teal));
  z-index: 9999;
  transition: width 0.08s linear;
}}

/* ── Header ────────────────────────────────────────────────────────────── */
.top-header {{
  position: fixed;
  top: 0; left: 0; right: 0;
  height: var(--header-h);
  background: var(--header-bg);
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border-bottom: 1px solid var(--border);
  display: flex;
  align-items: center;
  gap: 1rem;
  padding: 0 1.25rem 0 0;
  z-index: 200;
}}

.header-brand {{
  display: flex;
  align-items: center;
  gap: 0;
  width: var(--sidebar-w);
  min-width: var(--sidebar-w);
  padding: 0 1.25rem;
  border-right: 1px solid var(--border);
  height: 100%;
}}

.brand-logo {{
  display: flex;
  align-items: center;
  justify-content: center;
  width: 30px;
  height: 30px;
  background: linear-gradient(135deg, var(--accent), var(--teal));
  border-radius: 8px;
  font-size: 0.9rem;
  margin-right: 0.6rem;
  flex-shrink: 0;
  box-shadow: 0 0 12px var(--accent-glow);
}}

.brand-name {{
  font-size: 0.9rem;
  font-weight: 700;
  color: var(--text-primary);
  letter-spacing: -0.02em;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}}

.brand-version {{
  font-size: 0.65rem;
  color: var(--text-muted);
  background: var(--bg-raised);
  padding: 0.1rem 0.4rem;
  border-radius: 4px;
  border: 1px solid var(--border);
  margin-left: 0.5rem;
  flex-shrink: 0;
  font-family: 'JetBrains Mono', monospace;
}}

/* Header search */
.header-search {{
  flex: 1;
  max-width: 440px;
  position: relative;
  margin-left: 0.5rem;
}}

.search-input-wrap {{
  position: relative;
  display: flex;
  align-items: center;
}}

.search-icon {{
  position: absolute;
  left: 0.75rem;
  color: var(--text-muted);
  font-size: 0.8rem;
  pointer-events: none;
}}

#search-input {{
  width: 100%;
  background: var(--bg-raised);
  border: 1px solid var(--border);
  color: var(--text-primary);
  padding: 0.45rem 2.5rem 0.45rem 2.25rem;
  border-radius: 8px;
  font-size: 0.82rem;
  font-family: inherit;
  outline: none;
  transition: border-color 0.2s, box-shadow 0.2s;
}}

#search-input:focus {{
  border-color: var(--accent-light);
  box-shadow: 0 0 0 3px var(--accent-glow);
}}

#search-input::placeholder {{ color: var(--text-muted); }}

.search-kbd {{
  position: absolute;
  right: 0.6rem;
  font-size: 0.65rem;
  color: var(--text-muted);
  background: var(--bg-overlay);
  border: 1px solid var(--border);
  padding: 0.1rem 0.35rem;
  border-radius: 4px;
  font-family: 'JetBrains Mono', monospace;
  pointer-events: none;
}}

.search-results {{
  position: absolute;
  top: calc(100% + 8px);
  left: 0;
  width: 100%;
  min-width: 360px;
  background: var(--bg-raised);
  border: 1px solid var(--border);
  border-radius: 10px;
  box-shadow: 0 24px 48px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.03);
  display: none;
  z-index: 300;
  overflow: hidden;
  max-height: 420px;
  overflow-y: auto;
}}

.search-results-header {{
  padding: 0.5rem 0.75rem;
  font-size: 0.7rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.08em;
  border-bottom: 1px solid var(--border-muted);
}}

.search-result-item {{
  padding: 0.7rem 0.85rem;
  cursor: pointer;
  border-bottom: 1px solid var(--border-muted);
  transition: background 0.12s;
  display: flex;
  align-items: flex-start;
  gap: 0.6rem;
}}

.search-result-item:last-child {{ border-bottom: none; }}
.search-result-item:hover {{ background: var(--bg-hover); }}

.search-result-icon {{
  font-size: 0.75rem;
  color: var(--accent-light);
  margin-top: 2px;
  flex-shrink: 0;
}}

.search-result-title {{
  font-size: 0.82rem;
  font-weight: 500;
  color: var(--text-primary);
}}

.search-result-preview {{
  font-size: 0.72rem;
  color: var(--text-secondary);
  margin-top: 2px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 300px;
}}

/* Header right actions */
.header-actions {{
  margin-left: auto;
  display: flex;
  align-items: center;
  gap: 0.5rem;
}}

.header-btn {{
  display: flex;
  align-items: center;
  gap: 0.35rem;
  padding: 0.35rem 0.75rem;
  background: transparent;
  border: 1px solid var(--border);
  color: var(--text-secondary);
  border-radius: 6px;
  font-size: 0.78rem;
  font-family: inherit;
  cursor: pointer;
  transition: all 0.15s;
  white-space: nowrap;
}}

.header-btn:hover {{
  background: var(--bg-raised);
  color: var(--text-primary);
  border-color: var(--accent-light);
}}

.theme-toggle {{
  width: 32px;
  padding: 0.35rem;
  justify-content: center;
}}

/* ── Layout ────────────────────────────────────────────────────────────── */
.layout {{
  display: flex;
  margin-top: var(--header-h);
  min-height: calc(100vh - var(--header-h));
}}

/* ── Sidebar ───────────────────────────────────────────────────────────── */
.sidebar {{
  width: var(--sidebar-w);
  min-width: var(--sidebar-w);
  background: var(--sidebar-bg);
  border-right: 1px solid var(--sidebar-border);
  position: fixed;
  top: var(--header-h);
  bottom: 0;
  left: 0;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  padding-bottom: 2rem;
}}

.sidebar-section {{
  padding: 1.25rem 0.75rem 0.5rem;
}}

.sidebar-section-label {{
  font-size: 0.65rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--text-muted);
  padding: 0 0.5rem;
  margin-bottom: 0.35rem;
}}

.sidebar nav ul {{
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 1px;
}}

.nav-link {{
  display: flex;
  align-items: center;
  gap: 0.6rem;
  padding: 0.45rem 0.6rem;
  color: var(--text-secondary);
  text-decoration: none;
  border-radius: 6px;
  font-size: 0.82rem;
  font-weight: 400;
  transition: all 0.12s;
  position: relative;
}}

.nav-link:hover {{
  background: var(--bg-hover);
  color: var(--text-primary);
}}

.nav-link.active {{
  background: var(--accent-dim);
  color: var(--text-accent);
  font-weight: 500;
}}

.nav-link.active::before {{
  content: '';
  position: absolute;
  left: 0;
  top: 20%;
  bottom: 20%;
  width: 2px;
  background: var(--accent-light);
  border-radius: 0 2px 2px 0;
}}

.nav-icon {{
  font-size: 0.7rem;
  width: 16px;
  text-align: center;
  flex-shrink: 0;
  opacity: 0.7;
}}

/* Sidebar footer */
.sidebar-footer {{
  margin-top: auto;
  padding: 1rem 1.25rem;
  border-top: 1px solid var(--border-muted);
}}

.sidebar-footer-text {{
  font-size: 0.68rem;
  color: var(--text-muted);
  line-height: 1.6;
}}

/* ── Main content ──────────────────────────────────────────────────────── */
.main {{
  margin-left: var(--sidebar-w);
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
}}

/* ── Hero ──────────────────────────────────────────────────────────────── */
.hero {{
  position: relative;
  padding: 4rem 3.5rem 3rem;
  border-bottom: 1px solid var(--border);
  overflow: hidden;
}}

.hero::before {{
  content: '';
  position: absolute;
  top: -40%;
  right: -10%;
  width: 500px;
  height: 500px;
  background: radial-gradient(circle, var(--accent-glow) 0%, transparent 65%);
  pointer-events: none;
}}

.hero::after {{
  content: '';
  position: absolute;
  bottom: -30%;
  left: 30%;
  width: 300px;
  height: 300px;
  background: radial-gradient(circle, rgba(6,182,212,0.08) 0%, transparent 65%);
  pointer-events: none;
}}

.hero-eyebrow {{
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.72rem;
  color: var(--accent-light);
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  margin-bottom: 0.75rem;
}}

.hero-eyebrow::before {{
  content: '';
  display: block;
  width: 24px;
  height: 1px;
  background: var(--accent-light);
}}

.hero-title {{
  font-size: clamp(1.75rem, 3vw, 2.75rem);
  font-weight: 800;
  letter-spacing: -0.04em;
  line-height: 1.1;
  color: var(--text-primary);
  margin-bottom: 0.9rem;
}}

.hero-title span {{
  background: linear-gradient(135deg, var(--accent-light), var(--teal));
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}}

.hero-desc {{
  font-size: 1rem;
  color: var(--text-secondary);
  max-width: 580px;
  line-height: 1.7;
  margin-bottom: 1.5rem;
}}

.hero-badges {{
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 2rem;
}}

.badge {{
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  padding: 0.25rem 0.7rem;
  border-radius: 9999px;
  font-size: 0.72rem;
  font-weight: 600;
  border: 1px solid;
}}

.badge-dot {{
  width: 5px;
  height: 5px;
  border-radius: 50%;
}}

.badge-lang      {{ background: rgba(124,58,237,0.12); border-color: rgba(124,58,237,0.4); color: #a78bfa; }}
.badge-lang      .badge-dot {{ background: #a78bfa; }}
.badge-framework {{ background: rgba(6,182,212,0.10); border-color: rgba(6,182,212,0.35); color: #67e8f9; }}
.badge-framework .badge-dot {{ background: #67e8f9; }}
.badge-complexity{{ background: rgba(245,158,11,0.10); border-color: rgba(245,158,11,0.35); color: #fcd34d; }}
.badge-complexity .badge-dot {{ background: #fcd34d; }}
.badge-files     {{ background: rgba(16,185,129,0.10); border-color: rgba(16,185,129,0.35); color: #6ee7b7; }}
.badge-files     .badge-dot {{ background: #6ee7b7; }}

/* Hero stats */
.hero-stats {{
  display: flex;
  gap: 2rem;
}}

.stat {{
  display: flex;
  flex-direction: column;
}}

.stat-value {{
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--text-primary);
  letter-spacing: -0.03em;
  font-family: 'JetBrains Mono', monospace;
}}

.stat-label {{
  font-size: 0.72rem;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.06em;
}}

/* ── Content area ──────────────────────────────────────────────────────── */
.content-area {{
  max-width: 860px;
  padding: 0 3.5rem 6rem;
  width: 100%;
}}

/* ── Doc sections ──────────────────────────────────────────────────────── */
.doc-section {{
  padding: 3.5rem 0;
  border-bottom: 1px solid var(--border-muted);
}}

.doc-section:last-child {{ border-bottom: none; }}

.section-inner {{
  /* typography for generated content */
}}

/* ── Typography in sections ────────────────────────────────────────────── */
.section-inner h1 {{
  font-size: 1.75rem;
  font-weight: 800;
  letter-spacing: -0.04em;
  color: var(--text-primary);
  margin-bottom: 0.75rem;
  line-height: 1.2;
}}

.section-inner h2 {{
  font-size: 1.3rem;
  font-weight: 700;
  letter-spacing: -0.025em;
  color: var(--text-primary);
  margin: 2.5rem 0 1rem;
  padding-bottom: 0.6rem;
  border-bottom: 1px solid var(--border);
  display: flex;
  align-items: center;
  gap: 0.5rem;
}}

.section-inner h3 {{
  font-size: 1.05rem;
  font-weight: 600;
  color: var(--text-primary);
  margin: 2rem 0 0.75rem;
  display: flex;
  align-items: center;
  gap: 0.4rem;
}}

.section-inner h3::before {{
  content: '';
  display: block;
  width: 3px;
  height: 14px;
  background: var(--accent-light);
  border-radius: 2px;
  flex-shrink: 0;
}}

.section-inner h4 {{
  font-size: 0.85rem;
  font-weight: 600;
  color: var(--text-secondary);
  text-transform: uppercase;
  letter-spacing: 0.07em;
  margin: 1.75rem 0 0.5rem;
}}

.section-inner h5 {{
  font-size: 0.9rem;
  font-weight: 600;
  color: var(--text-accent);
  margin: 1.25rem 0 0.4rem;
}}

.section-inner p {{
  color: var(--text-secondary);
  line-height: 1.8;
  margin-bottom: 0.85rem;
  font-size: 0.92rem;
}}

.section-inner a {{
  color: var(--accent-light);
  text-decoration: none;
  border-bottom: 1px solid rgba(139,92,246,0.3);
  transition: border-color 0.15s;
}}

.section-inner a:hover {{ border-bottom-color: var(--accent-light); }}

/* Lists */
.section-inner ul, .section-inner ol {{
  padding-left: 1.4rem;
  margin-bottom: 0.85rem;
  display: flex;
  flex-direction: column;
  gap: 0.4rem;
}}

.section-inner li {{
  color: var(--text-secondary);
  font-size: 0.92rem;
  line-height: 1.7;
}}

.section-inner li::marker {{ color: var(--accent-light); }}

/* Blockquote */
.section-inner blockquote {{
  margin: 1.25rem 0;
  padding: 0.85rem 1.25rem;
  background: var(--bg-raised);
  border-left: 3px solid var(--accent-light);
  border-radius: 0 8px 8px 0;
}}

.section-inner blockquote p {{
  color: var(--text-secondary);
  margin: 0;
  font-style: italic;
}}

/* HR */
.section-inner hr {{
  border: none;
  border-top: 1px solid var(--border);
  margin: 2rem 0;
}}

/* Strong / Em */
.section-inner strong {{ color: var(--text-primary); font-weight: 600; }}
.section-inner em {{ color: var(--text-secondary); font-style: italic; }}

/* ── Code blocks ───────────────────────────────────────────────────────── */
.section-inner pre {{
  position: relative;
  background: var(--code-bg);
  border: 1px solid var(--code-border);
  border-radius: 10px;
  margin: 1.25rem 0;
  overflow: hidden;
}}

.code-header {{
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0.55rem 1rem;
  background: var(--bg-raised);
  border-bottom: 1px solid var(--code-border);
}}

.code-lang {{
  font-size: 0.68rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--text-muted);
  font-family: 'JetBrains Mono', monospace;
}}

.copy-btn {{
  background: transparent;
  border: 1px solid var(--border);
  color: var(--text-muted);
  padding: 0.2rem 0.6rem;
  border-radius: 5px;
  font-size: 0.68rem;
  cursor: pointer;
  font-family: 'JetBrains Mono', monospace;
  transition: all 0.15s;
  display: flex;
  align-items: center;
  gap: 0.3rem;
}}

.copy-btn:hover {{
  background: var(--accent-dim);
  border-color: var(--accent-light);
  color: var(--accent-light);
}}

.copy-btn.copied {{
  background: var(--green-dim);
  border-color: var(--green);
  color: var(--green);
}}

.section-inner pre code {{
  display: block;
  padding: 1.1rem 1.25rem;
  font-family: 'JetBrains Mono', monospace;
  font-size: 0.82rem;
  line-height: 1.7;
  color: var(--code-text);
  overflow-x: auto;
  background: none;
  border: none;
  border-radius: 0;
}}

/* Inline code */
.section-inner code {{
  font-family: 'JetBrains Mono', monospace;
  font-size: 0.82em;
  background: var(--inline-bg);
  color: var(--inline-text);
  padding: 0.15rem 0.45rem;
  border-radius: 5px;
  border: 1px solid var(--border);
}}

/* Syntax tokens */
.tok-keyword  {{ color: var(--syn-keyword); font-weight: 500; }}
.tok-string   {{ color: var(--syn-string); }}
.tok-comment  {{ color: var(--syn-comment); font-style: italic; }}
.tok-number   {{ color: var(--syn-number); }}
.tok-function {{ color: var(--syn-function); }}
.tok-class    {{ color: var(--syn-class); font-weight: 500; }}
.tok-decorator{{ color: var(--syn-decorator); }}
.tok-builtin  {{ color: var(--syn-builtin); }}
.tok-operator {{ color: var(--syn-operator); }}
.tok-self     {{ color: var(--syn-keyword); font-style: italic; }}

/* ── Tables ────────────────────────────────────────────────────────────── */
.section-inner .table-wrap {{
  overflow-x: auto;
  margin: 1.25rem 0;
  border-radius: 8px;
  border: 1px solid var(--border);
}}

.section-inner table {{
  width: 100%;
  border-collapse: collapse;
  font-size: 0.85rem;
}}

.section-inner th {{
  background: var(--bg-raised);
  padding: 0.65rem 0.9rem;
  text-align: left;
  font-size: 0.72rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.07em;
  color: var(--text-muted);
  border-bottom: 1px solid var(--border);
  white-space: nowrap;
}}

.section-inner td {{
  padding: 0.65rem 0.9rem;
  color: var(--text-secondary);
  border-bottom: 1px solid var(--border-muted);
  vertical-align: top;
  line-height: 1.6;
}}

.section-inner tr:last-child td {{ border-bottom: none; }}
.section-inner tr:hover td {{ background: var(--bg-hover); }}

/* ── Back to top ───────────────────────────────────────────────────────── */
#back-to-top {{
  position: fixed;
  bottom: 1.75rem;
  right: 1.75rem;
  width: 38px;
  height: 38px;
  background: var(--bg-raised);
  border: 1px solid var(--border);
  color: var(--text-secondary);
  border-radius: 8px;
  cursor: pointer;
  font-size: 0.9rem;
  display: none;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
  z-index: 100;
}}

#back-to-top:hover {{
  background: var(--accent-dim);
  border-color: var(--accent-light);
  color: var(--accent-light);
}}

#back-to-top.visible {{ display: flex; }}

/* ── Responsive ────────────────────────────────────────────────────────── */
@media (max-width: 900px) {{
  .sidebar {{ display: none; }}
  .main {{ margin-left: 0; }}
  .hero, .content-area {{ padding-left: 1.5rem; padding-right: 1.5rem; }}
  .header-brand {{ min-width: 0; width: auto; }}
  .brand-version {{ display: none; }}
  #search-input {{ width: 160px; }}
  .hero-stats {{ gap: 1.25rem; }}
}}
</style>
</head>
<body>

<div id="scroll-progress"></div>

<!-- ── Header ──────────────────────────────────────────────────────────── -->
<header class="top-header">
  <div class="header-brand">
    <div class="brand-logo">⚡</div>
    <span class="brand-name">{html_module.escape(project_name)}</span>
    <span class="brand-version">docs</span>
  </div>

  <div class="header-search">
    <div class="search-input-wrap">
      <span class="search-icon">🔍</span>
      <input type="text" id="search-input" placeholder="Search documentation..." autocomplete="off" spellcheck="false">
      <span class="search-kbd">⌘K</span>
    </div>
    <div class="search-results" id="search-results">
      <div class="search-results-header">Results</div>
    </div>
  </div>

  <div class="header-actions">
    <button class="header-btn" id="theme-toggle" title="Toggle theme">☀</button>
  </div>
</header>

<!-- ── Layout ──────────────────────────────────────────────────────────── -->
<div class="layout">

  <!-- Sidebar -->
  <aside class="sidebar">
    <div class="sidebar-section">
      <div class="sidebar-section-label">Documentation</div>
      <nav>
        <ul>
          {nav_items_html}
        </ul>
      </nav>
    </div>

    <div class="sidebar-footer">
      <div class="sidebar-footer-text">
        Generated {timestamp}<br>
        Agentic Doc Generator<br>
        Powered by Groq LLM + RAG
      </div>
    </div>
  </aside>

  <!-- Main -->
  <main class="main">

    <!-- Hero -->
    <div class="hero">
      <div class="hero-eyebrow">SDK Documentation</div>
      <h1 class="hero-title"><span>{html_module.escape(project_name)}</span></h1>
      <p class="hero-desc">{html_module.escape(description)}</p>
      <div class="hero-badges">{badges}</div>
      <div class="hero-stats">
        <div class="stat">
          <div class="stat-value">{total_files}</div>
          <div class="stat-label">Files Analyzed</div>
        </div>
        <div class="stat">
          <div class="stat-value">{feature_count}</div>
          <div class="stat-label">Features</div>
        </div>
        <div class="stat">
          <div class="stat-value">{dep_count}</div>
          <div class="stat-label">Dependencies</div>
        </div>
        <div class="stat">
          <div class="stat-value">{comp_count}</div>
          <div class="stat-label">Components</div>
        </div>
      </div>
    </div>

    <!-- Content -->
    <div class="content-area">
      {content_html}
    </div>

  </main>
</div>

<button id="back-to-top" title="Back to top">↑</button>

<script>
// ── State ──────────────────────────────────────────────────────────────────
let isDark = true;
const root = document.documentElement;

// ── Search index ───────────────────────────────────────────────────────────
const searchIndex = [];
document.querySelectorAll('.doc-section').forEach(sec => {{
  const id = sec.id;
  sec.querySelectorAll('h1,h2,h3,h4,h5').forEach(h => {{
    const next = h.nextElementSibling;
    searchIndex.push({{
      id,
      title: h.textContent.trim(),
      preview: next ? next.textContent.slice(0, 90).trim() : '',
      level: parseInt(h.tagName[1]),
    }});
  }});
}});

const searchInput   = document.getElementById('search-input');
const searchResults = document.getElementById('search-results');

function renderSearch(q) {{
  if (!q.trim()) {{ searchResults.style.display = 'none'; return; }}
  const matches = searchIndex
    .filter(i => i.title.toLowerCase().includes(q) || i.preview.toLowerCase().includes(q))
    .slice(0, 9);
  if (!matches.length) {{ searchResults.style.display = 'none'; return; }}
  const icons = ['◈','◈','▸','·','·'];
  searchResults.innerHTML = '<div class="search-results-header">Results</div>' +
    matches.map(m => `
      <div class="search-result-item" onclick="goTo('${{m.id}}')">
        <span class="search-result-icon">${{icons[m.level-1]||'·'}}</span>
        <div>
          <div class="search-result-title">${{esc(m.title)}}</div>
          <div class="search-result-preview">${{esc(m.preview)}}</div>
        </div>
      </div>`).join('');
  searchResults.style.display = 'block';
}}

searchInput.addEventListener('input', e => renderSearch(e.target.value.toLowerCase()));
searchInput.addEventListener('keydown', e => {{
  if (e.key === 'Escape') {{ searchResults.style.display = 'none'; searchInput.blur(); }}
}});
document.addEventListener('keydown', e => {{
  if ((e.metaKey || e.ctrlKey) && e.key === 'k') {{
    e.preventDefault(); searchInput.focus(); searchInput.select();
  }}
}});
document.addEventListener('click', e => {{
  if (!searchInput.contains(e.target) && !searchResults.contains(e.target))
    searchResults.style.display = 'none';
}});

function goTo(id) {{
  const el = document.getElementById(id);
  if (el) el.scrollIntoView({{ behavior: 'smooth', block: 'start' }});
  searchResults.style.display = 'none';
  searchInput.value = '';
}}

// ── Scroll: progress + active nav + back-to-top ───────────────────────────
const progressBar = document.getElementById('scroll-progress');
const navLinks    = document.querySelectorAll('.nav-link');
const sections    = document.querySelectorAll('.doc-section');
const backToTop   = document.getElementById('back-to-top');

window.addEventListener('scroll', () => {{
  const pct = window.scrollY / (document.body.scrollHeight - window.innerHeight) * 100;
  progressBar.style.width = pct + '%';

  let current = '';
  sections.forEach(s => {{ if (window.scrollY >= s.offsetTop - 100) current = s.id; }});
  navLinks.forEach(a => {{
    a.classList.toggle('active', a.getAttribute('href') === '#' + current);
  }});

  backToTop.classList.toggle('visible', window.scrollY > 500);
}}, {{ passive: true }});

backToTop.addEventListener('click', () => window.scrollTo({{ top: 0, behavior: 'smooth' }}));

navLinks.forEach(a => {{
  a.addEventListener('click', e => {{
    e.preventDefault();
    const t = document.querySelector(a.getAttribute('href'));
    if (t) t.scrollIntoView({{ behavior: 'smooth', block: 'start' }});
  }});
}});

// ── Theme toggle ──────────────────────────────────────────────────────────
const themeBtn = document.getElementById('theme-toggle');
themeBtn.addEventListener('click', () => {{
  isDark = !isDark;
  if (!isDark) {{
    root.style.setProperty('--bg-base',     '#ffffff');
    root.style.setProperty('--bg-surface',  '#f6f8fa');
    root.style.setProperty('--bg-raised',   '#eaeef2');
    root.style.setProperty('--bg-overlay',  '#d0d7de');
    root.style.setProperty('--bg-hover',    '#e1e4e8');
    root.style.setProperty('--sidebar-bg',  '#f6f8fa');
    root.style.setProperty('--sidebar-border','#d0d7de');
    root.style.setProperty('--text-primary','#1f2328');
    root.style.setProperty('--text-secondary','#656d76');
    root.style.setProperty('--text-muted',  '#8c959f');
    root.style.setProperty('--border',      '#d0d7de');
    root.style.setProperty('--border-muted','#eaeef2');
    root.style.setProperty('--code-bg',     '#f6f8fa');
    root.style.setProperty('--code-border', '#d0d7de');
    root.style.setProperty('--code-text',   '#1f2328');
    root.style.setProperty('--inline-bg',   '#eaeef2');
    root.style.setProperty('--inline-text', '#7c3aed');
    root.style.setProperty('--syn-comment', '#9a9a9a');
    root.style.setProperty('--syn-string',  '#0550ae');
    root.style.setProperty('--syn-keyword', '#cf222e');
    root.style.setProperty('--syn-number',  '#0550ae');
    root.style.setProperty('--syn-function','#8250df');
    root.style.setProperty('--syn-class',   '#953800');
    root.style.setProperty('--header-bg',   'rgba(246,248,250,0.92)');
    themeBtn.textContent = '🌙';
  }} else {{
    location.reload();
  }}
}});

// ── Code block headers + copy buttons ────────────────────────────────────
document.querySelectorAll('pre').forEach(pre => {{
  const code = pre.querySelector('code');
  if (!code) return;
  const lang = (code.className.match(/language-(\w+)/) || [])[1] || 'code';

  const header = document.createElement('div');
  header.className = 'code-header';

  const langSpan = document.createElement('span');
  langSpan.className = 'code-lang';
  langSpan.textContent = lang;

  const copyBtn = document.createElement('button');
  copyBtn.className = 'copy-btn';
  copyBtn.innerHTML = '⎘ copy';
  copyBtn.addEventListener('click', () => {{
    navigator.clipboard.writeText(code.innerText).then(() => {{
      copyBtn.innerHTML = '✓ copied';
      copyBtn.classList.add('copied');
      setTimeout(() => {{ copyBtn.innerHTML = '⎘ copy'; copyBtn.classList.remove('copied'); }}, 2000);
    }});
  }});

  header.appendChild(langSpan);
  header.appendChild(copyBtn);
  pre.insertBefore(header, pre.firstChild);
}});

// ── Wrap tables ───────────────────────────────────────────────────────────
document.querySelectorAll('.section-inner table').forEach(t => {{
  const wrap = document.createElement('div');
  wrap.className = 'table-wrap';
  t.parentNode.insertBefore(wrap, t);
  wrap.appendChild(t);
}});

// ── Syntax highlighting ───────────────────────────────────────────────────
document.querySelectorAll('pre code').forEach(block => {{
  let h = block.innerHTML;
  const lang = (block.className || '').replace('language-','').toLowerCase();

  // Decorators (Python)
  h = h.replace(/(@[\w.]+)/g, '<span class="tok-decorator">$1</span>');
  // Comments
  if (['python','bash','sh','ruby','r'].includes(lang))
    h = h.replace(/(#[^\n<]*)/g, '<span class="tok-comment">$1</span>');
  if (['js','javascript','ts','typescript','java','go','rust','cpp','c'].includes(lang))
    h = h.replace(/(\/\/[^\n<]*)/g, '<span class="tok-comment">$1</span>');
  // Multi-line comments
  h = h.replace(/(\/\*[\s\S]*?\*\/)/g, '<span class="tok-comment">$1</span>');
  // Strings (double, single, backtick)
  h = h.replace(/("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|`(?:[^`\\]|\\.)*`)/g, '<span class="tok-string">$1</span>');
  // Keywords
  const kw = /\b(def|class|import|from|return|if|elif|else|for|while|try|except|finally|with|as|in|not|and|or|is|None|True|False|async|await|yield|pass|break|continue|raise|lambda|global|nonlocal|assert|del|const|let|var|function|=&gt;|export|default|interface|type|struct|fn|pub|mod|use|impl|trait|enum|match|self|super|new|this|void|null|undefined|static|extends|implements|abstract|override|readonly|protected|private|public|package|switch|case|goto|defer|chan|select|mut|ref|move|where|forall)\b/g;
  h = h.replace(kw, '<span class="tok-keyword">$1</span>');
  // self/this
  h = h.replace(/\b(self|this)\b/g, '<span class="tok-self">$1</span>');
  // Numbers
  h = h.replace(/\b(\d+\.?\d*(?:[eE][+-]?\d+)?)\b/g, '<span class="tok-number">$1</span>');
  // Function/method calls
  h = h.replace(/\b([a-z_]\w*)\s*(?=\()/g, '<span class="tok-function">$1</span>');
  // Class names (CamelCase)
  h = h.replace(/\b([A-Z][a-zA-Z0-9_]+)\b/g, '<span class="tok-class">$1</span>');
  // Built-ins
  h = h.replace(/\b(print|len|range|list|dict|set|tuple|str|int|float|bool|type|isinstance|hasattr|getattr|setattr|open|map|filter|zip|enumerate|sorted|reversed|sum|max|min|abs|round|input|format|repr|id|hash|hex|oct|bin|callable|iter|next|super|property|classmethod|staticmethod|object)\b/g, '<span class="tok-builtin">$1</span>');

  block.innerHTML = h;
}});

// ── Utility ───────────────────────────────────────────────────────────────
function esc(s) {{
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}}
</script>
</body>
</html>"""


# ---------------------------------------------------------------------------
# Markdown → HTML
# ---------------------------------------------------------------------------

def _markdown_to_html(md: str) -> str:
    md = re.sub(r"<!--.*?-->", "", md, flags=re.DOTALL)
    lines  = md.split("\n")
    output = []
    i = 0
    in_code  = False
    code_lang  = ""
    code_lines = []

    while i < len(lines):
        line = lines[i]

        # Code fence
        if line.startswith("```"):
            if in_code:
                escaped = html_module.escape("\n".join(code_lines))
                output.append(f'<pre><code class="language-{html_module.escape(code_lang)}">{escaped}</code></pre>')
                in_code = False; code_lines = []; code_lang = ""
            else:
                in_code = True
                code_lang = line[3:].strip() or "text"
            i += 1; continue

        if in_code:
            code_lines.append(line); i += 1; continue

        # Headings
        m = re.match(r"^(#{1,5})\s+(.*)", line)
        if m:
            level = len(m.group(1))
            text  = _inline(m.group(2))
            output.append(f"<h{level}>{text}</h{level}>")
            i += 1; continue

        # HR
        if re.match(r"^(-{3,}|\*{3,}|_{3,})$", line.strip()):
            output.append("<hr>"); i += 1; continue

        # Blockquote
        if line.startswith("> "):
            bq_lines = []
            while i < len(lines) and lines[i].startswith("> "):
                bq_lines.append(lines[i][2:])
                i += 1
            inner = _markdown_to_html("\n".join(bq_lines))
            output.append(f"<blockquote>{inner}</blockquote>")
            continue

        # Unordered list
        if re.match(r"^[-*+] ", line):
            items = []
            while i < len(lines) and re.match(r"^[-*+] ", lines[i]):
                items.append(f"<li>{_inline(lines[i][2:])}</li>"); i += 1
            output.append("<ul>" + "".join(items) + "</ul>")
            continue

        # Ordered list
        if re.match(r"^\d+\.\s", line):
            items = []
            while i < len(lines) and re.match(r"^\d+\.\s", lines[i]):
                clean_line = re.sub(r'^\d+\.\s', '', lines[i])
                items.append(f"<li>{_inline(clean_line)}</li>")
                i += 1
            output.append("<ol>" + "".join(items) + "</ol>")
            continue

        # Table
        if "|" in line and i + 1 < len(lines) and re.match(r"^\|?[\s\-:]+\|", lines[i+1]):
            headers = [h.strip() for h in line.strip("|").split("|")]
            i += 2  # skip separator
            rows = []
            while i < len(lines) and "|" in lines[i] and not re.match(r"^\|?[\s\-:]+\|", lines[i]):
                cells = [c.strip() for c in lines[i].strip("|").split("|")]
                rows.append(cells); i += 1
            thead = "<tr>" + "".join(f"<th>{_inline(h)}</th>" for h in headers) + "</tr>"
            tbody = "".join(
                "<tr>" + "".join(f"<td>{_inline(c)}</td>" for c in row) + "</tr>"
                for row in rows
            )
            output.append(f"<table><thead>{thead}</thead><tbody>{tbody}</tbody></table>")
            continue

        # Empty
        if not line.strip():
            output.append(""); i += 1; continue

        # Paragraph
        para = []
        while i < len(lines) and lines[i].strip():
            l = lines[i]
            if (l.startswith("```") or re.match(r"^#{1,5} ", l) or
                    re.match(r"^[-*+] ", l) or re.match(r"^\d+\.\s", l) or
                    re.match(r"^(-{3,}|\*{3,})$", l.strip()) or
                    l.startswith("> ") or ("|" in l and i+1 < len(lines) and re.match(r"^\|?[\s\-:]+\|", lines[i+1] if i+1 < len(lines) else ""))):
                break
            para.append(l); i += 1
        if para:
            output.append(f"<p>{_inline(' '.join(para))}</p>")
        continue

    if in_code and code_lines:
        escaped = html_module.escape("\n".join(code_lines))
        output.append(f'<pre><code class="language-{html_module.escape(code_lang)}">{escaped}</code></pre>')

    return "\n".join(output)


def _inline(text: str) -> str:
    text = html_module.escape(text)
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"__(.+?)__",     r"<strong>\1</strong>", text)
    # Italic
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    text = re.sub(r"_(.+?)_",   r"<em>\1</em>", text)
    # Inline code
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    # Links
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    return text